version: '3.3'

services:
  api:
    container_name: evolution_api
    image: davidsongomes/evolution-api:latest
    restart: always
    ports:
      - 8888:8888
    volumes:
      - /opt/evolution/instances:/evolution/instances
      - /opt/evolution/store:/evolution/store
    networks:
      - evolution-net
    env_file:
      - ./Docker/.env
    command: ['node', './dist/src/main.js']

# volumes:
#   evolution_instances:
#     external: true
#   evolution_store:
#     external: true

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
